Makefile.in: add missing dependency on bits/sysnum.h to $(pregen-headers-y)
This fixes the following build error:

  GEN include/bits/sysnum.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/structsem.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/lowlevelrobustlock.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/lowlevelbarrier.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/structsem.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/lowlevelrobustlock.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/pthread-pi-defines.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/lowlevelbarrier.h
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/pthread-pi-defines.h
In file included from ./libpthread/nptl/pthreadP.h:25:0,
                 from <stdin>:2:
./include/sys/syscall.h:24:25: fatal error: bits/sysnum.h: No such file or directory
 #include <bits/sysnum.h>
                         ^
compilation terminated.
  GEN libpthread/nptl/sysdeps/unix/sysv/linux/lowlevelcond.h
make[1]: *** [libpthread/nptl/sysdeps/unix/sysv/linux/lowlevelrobustlock.h] Error 1

Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>