libcrypt: add missing errno.h header
Fixes:
libcrypt/crypt.c:29:15: error: 'EINVAL' undeclared (first use in this function)
   __set_errno(EINVAL);
               ^~~~~~

Signed-off-by: Yann Sionneau <ysionneau@kalray.eu>