utimes: force to use 64-bit implementation if available and requested (part II)
- fix dependency for libc_hidden_def(utimes) statement, fixes (on ARM-64bit):

  ./include/libc-symbols.h:431:32: error: '__EI_utimes' aliased to undefined symbol '__GI_utimes'
    431 |         extern __typeof (name) __EI_##name __attribute__((alias (__hidden_asmname1 (,#local)))) \
        |                                ^~~~~
  ./include/libc-symbols.h:435:41: note: in expansion of macro '__hidden_ver1'
    435 | #  define hidden_def(name)              __hidden_ver1(__GI_##name, name, name);
        |                                         ^~~~~~~~~~~~~
  ./include/libc-symbols.h:503:32: note: in expansion of macro 'hidden_def'
    503 | # define libc_hidden_def(name) hidden_def (name)
        |                                ^~~~~~~~~~
  libc/sysdeps/linux/common/utimes.c:54:1: note: in expansion of macro 'libc_hidden_def'
     54 | libc_hidden_def(utimes)
        | ^~~~~~~~~~~~~~~

- fix dependency for 64-bit implementation, fixes (on ARM-64bit):

  .../build/busybox-1.37.0/libbb/copy_file.c:433:(.text.copy_file+0x2b0): undefined reference to `utimes'

Fixes: 48591e2a2 ("Provide fixups for riscv32.")
Fixes: 5aee86ed3 ("utimes: force to use 64-bit implementation if available and requested")
Signed-off-by: Peter Seiderer <ps.report@gmx.net>