libc/sysdeps/linux/common/utime.c: fix riscv32 build
Commit 48591e2a259d84247ae38f050bd58e6f7450bb77 forgot to update utime.c
resulting in the following riscv32 build failure with applications using
utime such as bzip2:

/home/buildroot/autobuild/instance-0/output-1/host/riscv32-buildroot-linux-uclibc/bin/ld.real: bzip2.o: in function `copyFileName':
bzip2.c:(.text+0x1fcc): undefined reference to `utime'

Fixes: 48591e2a259d84247ae38f050bd58e6f7450bb77
 - http://autobuild.buildroot.org/results/2e37d4e0bcef515fe9e643737419bfd26aa2833e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>