rtld: Compile with -fno-unwind-tables -fno-asynchronous-unwind-tables
Otherwise we have link errors because of unresolved refs in libgcc.a:

ld: /lib/gcc/arm-none-uclinuxfdpiceabi/9.0.0/libgcc.a(pr-support.o): in function `_Unwind_GetDataRelBase':
/libgcc/config/arm/pr-support.c:378: undefined reference to `abort'
ld: /lib/gcc/arm-none-uclinuxfdpiceabi/9.0.0/libgcc.a(unwind-arm.o): in function `unwind_phase2_forced':
/libgcc/unwind-arm-common.inc:511: undefined reference to `memcpy'

	* ldso/ldso/Makefile.in (CFLAGS-rtld): Always use
	-fno-unwind-tables -fno-asynchronous-unwind-tables on arm

Signed-off-by: Christophe Lyon <christophe.lyon@st.com>