linuxthreads: fix compile error for non-MMU
Otherwise you get following linking error, because
of missing functions in libc.a:
undefined reference to `__libc_enable_asynccancel'

Fix by Thorsten Glaser while hacking session.