Revert "tgmath.h: disable builtins"
This reverts commit d1671548b968103f4df1b80659e60ae1fc5a67b3.

You get following errors while compiling freeswitch:
awgn.c: In function 'awgn_init_dbov':                                                                                   awgn.c:110:5: error: void value not ignored as it ought to be                                                                s->rms = pow(10.0, level/20.0)*32768.0;

Reverting this commit allows to build the code.